class GameOver(Exception):
    def ValueError(self):
        pass


class EnemyDown(Exception):
    pass
